name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feat'
  - title: 'ğŸ› Hotfixes'
    label: 'fix'
  - title: 'ğŸ”§ Refactors'
    label: 'refactor'
  - title: 'ğŸ“ƒ Docs'
    label: 'docs'
  - title: 'ğŸ“¦ Chore'
    label: 'chore'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Describe changes
  $CHANGES
  ### Issue ticket number and link (optional)
