name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feat'
  - title: 'ğŸ› Hotfixes'
    label: 'fix'
  - title: 'ğŸ”§ Refactors'
    label: 'refactor'
  - title: 'ğŸ“ƒ Docs'
    label: 'docs'
  - title: 'ğŸ“¦ Chore'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # add '#' and '@' to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Describe changes
  
  $CHANGES
